### PR TITLE
Nullish coalescing support

### PR DESCRIPTION
**Pull request by sanex3339**

### CODE REVIEW

**Comment by sanex3339** [comment]
If someone will try to resolve all conflicts, i'll be happy, I'll try to do this later

**Comment by sanex3339** [comment]
Seems i have to recreate all this PRs based on this `wallabyjs/escodegen` to prevent conflicts.
But I'll need to be sure this will be merged, not like this https://github.com/estools/escodegen/pull/417

**Comment by ArtemGovorov** [comment]
Hey @sanex3339, Nullish coalescing support has already been implemented: https://github.com/wallabyjs/escodegen/commit/c9caffb00a5737bbd5143102001eacff82888261

**Comment by ArtemGovorov** [comment]
Some background: this fork had been originally created for use in our products https://wallabyjs.com and https://quokkajs.com/, and while we have been maintaining it (and are planning to keep maintaining it, and adding new features, etc.), we haven't bothered to keep it up-to-date with the original repo, also tests for our changes since we've forked are located in other (closed source) repos. 

If you like, please feel free to bring all the tests from the original `escodegen` over (including yours), because this repo is not going anywhere, will be maintained and developed and will stay open source.

**Pull request closed without merging**
